### ISSUE TITLE
bad paths in vignettes/figs

### ISSUE THREAD

**Issue by vjcitn** [chrarnold/GRaNIE#2]
```
vignettes/figs/file_list_png:/g/scb2/zaugg/carnold/Projects/GRN_pipeline/src/GRaNIE/vignettes/figs/TFPeak_fdr_perm/p-40.png
```
this can't work.

**Comment by vjcitn** [comment]
If possible, please run R CMD check on a system that is independent of the one on which you developed the code, to expose conditions like this.

**Comment by chrarnold** [comment]
I may have overseen this, thanks for pointing this out, will check the vignette. I am not sure what the best way here is, though: The pipeline produces various PDF files, and in the vignette, I want to include the figures from the PDF to show the user what they mean. There seems to be no direct way of importing PDFs into a Markdown, so what I did was to generate images for each PDF and each page, and then include the images in the vignette. A bit complicated, I am not happy about it, but what would be better way that is also ok for Bioconductor?

**Comment by chrarnold** [comment]
Actually, in none of the vignetets there is any absolute path. The file you mentioned I will exclude from the repo, this is just a file that lists all generated image files, it is never referenced anywhere and will not lead to any errors, it just doesnt belong to the repository

**Comment by chrarnold** [comment]
I am closing this issue as I think this is resolved as the file has been removed. Please feel free to re-open if necessary, or let me know - thanks a lot for reporting and being active here!
